// Schéma de validation Zod pour les biens immobiliers
import { z } from 'zod';

export const propertySchema = z.object({
  name: z.string().min(2, 'Le nom du bien doit faire au moins 2 caractères'),
  address: z.string().min(1, "L'adresse est requise"),
  city: z.string().min(1, 'La ville est requise'),
  postal_code: z.string().regex(/^\d{5}$/, 'Code postal invalide (5 chiffres)'),
  building: z.string().optional().nullable(),
  floor: z.string().optional().nullable(),
  door: z.string().optional().nullable(),
  property_type: z.string().default('Appartement'),
  furnished_type: z.string().default('Location vide'),
  surface: z.coerce.number().positive('La surface doit être positive').optional().nullable(),
  number_of_rooms: z.coerce.number().int().positive().optional().nullable(),
  kitchen_type: z.string().optional().nullable(),
  kitchen_equipment: z.array(z.string()).default([]),
  has_cellar: z.boolean().default(false),
  cellar_number: z.string().optional().nullable(),
  has_parking: z.boolean().default(false),
  parking_type: z.string().optional().nullable(),
  parking_number: z.string().optional().nullable(),
  has_balcony: z.boolean().default(false),
  balcony_surface: z.coerce.number().positive().optional().nullable(),
  has_terrace: z.boolean().default(false),
  terrace_surface: z.coerce.number().positive().optional().nullable(),
  has_garden: z.boolean().default(false),
  garden_surface: z.coerce.number().positive().optional().nullable(),
  garden_type: z.string().optional().nullable(),
  has_attic: z.boolean().default(false),
  heating_type: z.string().optional().nullable(),
  heating_energy: z.string().optional().nullable(),
  hot_water_type: z.string().optional().nullable(),
  hot_water_energy: z.string().optional().nullable(),
  charges_included: z.array(z.string()).default([]),
  charges_other: z.string().optional().nullable(),
  glazing_type: z.string().optional().nullable(),
  shutters_type: z.string().optional().nullable(),
  has_intercom: z.boolean().default(false),
  has_fiber: z.boolean().default(false),
  rent_amount: z.coerce.number().min(0, 'Le loyer doit être un nombre positif'),
  charges_amount: z.coerce.number().min(0, 'Les charges doivent être un nombre positif').default(0),
  deposit_amount: z.coerce.number().min(0, 'Le dépôt doit être un nombre positif').default(0),
  image_url: z.string().url('URL invalide').or(z.literal('')).optional().nullable(),
  images: z.array(z.string()).default([]),
});

export type PropertyFormData = z.infer<typeof propertySchema>;
